titles = [
    "ChEESE",
    "MaxPower",
    "9000-Layers",
    "CVPR-Ready",
    "Excellent",
    "GNU/Linux",
    "Soft",
    "Hard",
    "LeCun",
    "Bengio",
    "Hinton",
    "Schmidhuber"
    "Fast",
    "HyperDeep",
    "Wasserstein",
    "YOLO",
    "ROFLMAO",
    "MARVEL",
    "Wonder",
    "Matrix",
    "Trinity",
    "God",
    "Diffusion",
    "AGI",
    "Madman",
    "CRAZY",
    "StrongAI",
    "SoftAI",
    "WeakAI",
    "Vision",
    "BetterEye",
    "Weather",
    "Satellite",
    "Driver",
    "Amazing",
    "Great",
    "DeepBlue",
    "NONAME",
    "[ReplaceBeforeSubmission]",
    "Brain",
    "Universal",
    "Killer",
]

tasks = [
    "classification",
    "detection",
    "segmentation",
    "instance segmentation",
    "removal",
    "inpainting",
    "topic modeling",
    "style transfer",
    "super-resolution",
    "denoising",
    "zero-shot learning",
    "retrieval",
]

things = [
    "rabbits",
    "cats",
    "microwaves",
    "alien signals",
    "racism",
    "bats",
    "super-heroes",
    "mac&cheese",
    "glasses",
    "beer cans",
    "outliers",
    "nanorobots",
    "lost treasures",
    "chickens",
    "dogs",
    "raccoons",
    "thiefs",
    "hair",
    "majijuana",
    "vehicles",
    "Boeing 737-MAX",
    "fake money",
    "giftable Eiffel Tower miniatures",
    "anomalies",
    "radioactivty",
    "bombs",
    "cheesecackes",
    "insulting tweets",
    "forgotten passwords",
    "gold bars",
    "money",
    "salmon",
    "sushi",
    "books",
    "child",
    "record"
]

datas = [
    "RGB images",
    "brain-electro-activities",
    "children books",
    "fisheye videos",
    "Dailymotion comments",
    "Reddit usernames",
    "open source code",
    "satellite images",
    "3D point clouds",
    "missing data",
    "StreetView panoramas",
    "Tinder profile pictures",
    "vacation pictures",
    "autonomous vehicles sensors",
    "PET scans",
    "3D models",
    "stereo imaging",
    "RGB-D data",
    "raw Apache logs",
    "disassembled Java",
    "ATM receipts",
    "traffic cameras",
    "user webcams",
    "HDR pictures",
    "3D movies",
    "radar, sonar and that last one that uses light",
    "NASA photos",
    "digital paintings",
    "Photoshopped videos",
    "intrusion logs",
    "multispectral data",
    "black&white sketches",
    "children drawings",
]

adjectives = [
    "new",
    "reinforcement learning of",
    "lightweight",
    "scalable",
    "embedded",
    "deep",
    "adversarial",
    "residual",
    "convolutional",
    "recurrent",
    "bio-inspired",
    "spiking",
    "generative",
    "adversarial",
]

data_qualifiers = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "noisy labeled",
    "industrial",
    "expensive",
    "unlabeled",
    "scarce",
    "anomalous",
    "rare",
    "crowdsourced",
    "simulated",
]
task_qualifiers = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "improving",
    "pushing further",
    "better",
    "SOTA",
    "weakly-supervised",
    "semi-supervised",
    "improved",
    "enhanced",
    "fine-grained",
]

